### ISSUE TITLE
User and Group access please!

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-bitbucket#8]
Terraform 0.10+

Great resource, but badly needs User/Group management resource on a repository as this is one of the most fundamental aspects you want to manage. 

It would be awesome if terraform-provider-bitbucket could provide functionality to manage the user/group management of the repo (not just the Owner of the repo)

**Comment by cwood** [comment]
Sorry to have negative information. But essentially we are gonna be removing all of the 1.0 API's soon(can't give specifics - watch for a blog post). It has become a philosophical discussion to not allow add-ons to manage users/groups since it can lead to credentials with access to a user/team account that can be hard to track down when access to an account is revoked. This is out of my hands since this has been more of a product decision.
